def pass = "Pass"
def fail = "Fail"
def generalUtil
def jsUtil

pipeline {
    agent any

    tools {nodejs 'Node'}

    parameters {
        string(name: 'PR_BRANCH', defaultValue: '', description: '')
        string(name: 'PR_DESTINATION_BRANCH', defaultValue: '', description: '')
        string(name: 'PR_REPO_HTML', defaultValue: '', description: '')
        string(name: 'PR_REPO_NAME', defaultValue: '', description: '')
        string(name: 'PR_COMMIT', defaultValue: '', description: '')
        string(name: 'PR_PROJECT', defaultValue: '', description: '')
        string(name: 'PR_STATE', defaultValue: '', description: '')
        string(name: 'TEST_RUN', defaultValue: 'Y', description: 'This is a test run trigger. Fill in the parameter form with \'Y\' to run the pipeline without commit changes.') //Default value added while we build this pipeline
    }

    triggers {
        GenericTrigger(
            genericVariables: [
                [key: 'PR_BRANCH', value: '$.pullrequest.source.branch.name'],
                [key: 'PR_DESTINATION_BRANCH', value: '$.pullrequest.destination.branch.name'],
                [key: 'PR_REPO_HTML', value: '$.repository.links.self.href'],
                [key: 'PR_REPO_NAME', value: '$.repository.name'],
                [key: 'PR_COMMIT', value: '$.pullrequest.source.commit.hash'],
                [key: 'PR_PROJECT', value: '$.repository.full_name'],
                [key: 'PR_STATE', value: '$.pullrequest.state']
            ],

            tokenCredentialId: 'trigger-token',
            regexpFilterText: '$PR_STATE',
            regexpFilterExpression: 'OPEN'
        )
    }

    environment {
        CI_PIPELINE = "true"
        PROJECT_DIR = "${WORKSPACE}\\JS_Project" 
        REPORT_DIR = "${WORKSPACE}/PRJob/${PR_BRANCH}/Build_${BUILD_NUMBER}"
        JOB_REPO = "${PR_REPO_HTML}"
        BITBUCKET_ACCESS_TOKEN = credentials('bitbucket-access-token')
        JENKINS_API_KEY = credentials('jenkins-api-key')
        REPO_SSH = "git@bitbucket.org:${PR_PROJECT}.git"
        DESTINATION_BRANCH = "${PR_DESTINATION_BRANCH}"
    }

    stages {
        // Prepare Workspace: Environment Setup, Workspace Preparation(Branch Management), Unity Setup, Initial running the project on Unity Editor
        stage('Prepare Workspace') {
            steps {
                //send 'In Progress' status to Bitbucket
                script {
                    // print jenkins env configurations
                    sh 'env'
                    generalUtil = load("${WORKSPACE}/groovy/generalHelper.groovy")
                    jsUtil = load("${WORKSPACE}/groovy/jsHelper.groovy")

                    env.COMMIT_HASH = generalUtil.validateCommitHashes(WORKSPACE, PROJECT_DIR, PR_COMMIT, TEST_RUN)
                    echo env.COMMIT_HASH
                    generalUtil.initializeEnvironment(WORKSPACE, env.COMMIT_HASH, PR_BRANCH, PROJECT_DIR)

                    generalUtil.cloneOrUpdateRepo(PROJECT_DIR, REPO_SSH, PR_BRANCH)

                    generalUtil.mergeBranchIfNeeded()
                    generalUtil.checkoutBranch(PROJECT_DIR, PR_BRANCH) 

                    // Save directories pipeline is going to test. unique to JS pipeline
                    env.TEST_DIRECTORIES = jsUtil.findTestingDirs(PROJECT_DIR)
                    echo "Testing directories: ${env.TEST_DIRECTORIES}"

                    // Copy Centered Test Report link to this PR pipeline
                    echo "Report copied to ${REPORT_DIR}"
                    bat "if not exist \"${WORKSPACE}\\PRJob\\${PR_BRANCH}\\Build_${BUILD_NUMBER}\" mkdir \"${WORKSPACE}\\PRJob\\${PR_BRANCH}\\Build_${BUILD_NUMBER}\""
                    bat "copy \"${WORKSPACE}\\PRJob\\reports.html\" \"${WORKSPACE}\\PRJob\\${PR_BRANCH}\\Build_${BUILD_NUMBER}\\reports.html\""
                } 
            }
        }
        stage('Install Dependencies'){
            steps {
                script {    
                    //MUST USE BAT for npm commands, otherwise jenkins tries to use WSL for a linux distro                
                    echo "Dependencies step"
                    echo "Check NPM"

                    jsUtil.checkNodeVersion()

                    echo 'Install dependencies in testing directories'
                    jsUtil.installNpmInTestingDirs(env.TEST_DIRECTORIES)

                    // Change back to default directory
                    bat(script: 'cd "' + WORKSPACE + '"') 
                }
            }
        }
        stage('Linting'){
            steps {
                dir ("${REPORT_DIR}") {
                    sh "mkdir -p linting_results"
                }
                script {
                    echo "Linting step"
                    //surrounded the whole block in catch error incase publishing fails
                    catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){
                        jsUtil.executeLintingInTestingDirs(env.TEST_DIRECTORIES, REPORT_DIR, true, false)
                        generalUtil.publishTestResultsHtmlToWebServer(FOLDER_NAME, TICKET_NUMBER, "${REPORT_DIR}/linting_result", "Linting", BUILD_NUMBER)
                    }
                }
            }
        }
        // Runs the project's EditMode tests, and then generates a test report and a code coverage report.
        // Sends the test results to Bitbucket once the tests complete.
        stage('Tests') {
            steps {
                script {
                    echo "Testing step"
                }
            }
        }
        // Merges the two coverage reports from the EditMode and PlayMode (editor) reports into one.
        // Then sends a coverage report to Bitbucket.
        stage('Generate Code Coverage Report') {
            steps {
                script {
                    echo "Code Coverage step"
                }
            }
        }
        //Builds the project and saves it. containerization?
        stage('Build Project') {
            steps {
                script {
                    echo "Build Step"
                }
            }
        }
    }

    // When the pipeline finishes, sends the build status to Bitbucket.
    post {
        success {
            script {
                generalUtil.sendBuildStatus(WORKSPACE, "SUCCESSFUL", COMMIT_HASH, false, true)
            }
        }
        failure {
            script {
                generalUtil.sendBuildStatus(WORKSPACE, "FAILED", COMMIT_HASH, false, true)
            }
        }
        aborted {
            script {
                generalUtil.sendBuildStatus(WORKSPACE, "STOPPED", COMMIT_HASH, false, true)
            }
        }
    }
}